# Generated by Django 4.0.4 on 2022-05-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
