# Generated by Django 4.0.4 on 2022-05-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_like_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
