# Generated by Django 4.0.4 on 2022-05-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_like_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
